// spec §3.2 — auto-detect the GitHub Projects V2 board for the current repo and
// record it in .claude/shared/github-project-ids.md (a LOCAL_FILES path).
//
//   ai-pipe detect [<dir>]
//
// Preconditions (each a clear E_BAD_USAGE/E_VALIDATION, not a crash):
//   - gh CLI present and authenticated (`gh auth status`)
//   - org resolvable from .claude/rules/project-settings.md (`- **org**: X`)
// Then `gh project list --owner <org> --format json` enumerates the boards.

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { AiPipeError } from "./errors.js";
import { errMsg, resolveTargetDir } from "./utils.js";

// Pull `- **org**: <value>` out of project-settings.md, ignoring the
// {{ORG}} placeholder of a freshly-initialized (unfilled) install.
export function parseOrg(settingsMd: string): string | null {
  const m = settingsMd.match(/^\s*-\s*\*\*org\*\*:\s*(\S+)/m);
  const org = m?.[1];
  if (!org || org.startsWith("{{")) return null;
  return org;
}

export async function runDetect(args: string[]): Promise<void> {
  const target = resolveTargetDir(args.find((a) => !a.startsWith("-")));
  const settingsPath = join(target, ".claude", "rules", "project-settings.md");
  if (!existsSync(settingsPath)) {
    throw new AiPipeError("E_BAD_USAGE", `detect: no project-settings.md at ${settingsPath} (run \`ai-pipe init\` first)`, 2);
  }
  const org = parseOrg(readFileSync(settingsPath, "utf8"));
  if (org === null) {
    throw new AiPipeError("E_BAD_USAGE", "detect: org is unset/placeholder in project-settings.md — fill **org** first", 2);
  }

  // gh present + authenticated
  try {
    execFileSync("gh", ["auth", "status"], { stdio: ["ignore", "ignore", "ignore"] });
  } catch (e) {
    throw new AiPipeError("E_VALIDATION", `detect: gh CLI missing or not authenticated — run \`gh auth login\` (${errMsg(e)})`, 1);
  }

  let raw: string;
  try {
    raw = execFileSync("gh", ["project", "list", "--owner", org, "--format", "json"], {
      stdio: ["ignore", "pipe", "pipe"],
    }).toString();
  } catch (e) {
    throw new AiPipeError("E_VALIDATION", `detect: \`gh project list\` failed for owner ${org} (${errMsg(e)})`, 1);
  }

  let projects: unknown;
  try {
    projects = JSON.parse(raw);
  } catch (e) {
    throw new AiPipeError("E_VALIDATION", `detect: unparseable gh output (${errMsg(e)})`, 1);
  }
  const items = isProjectList(projects) ? projects.projects : [];

  const outPath = join(target, ".claude", "shared", "github-project-ids.md");
  const lines = [
    "<!-- generated by `ai-pipe detect` — spec §3.2. LOCAL_FILES (not overwritten by update). -->",
    "",
    `# GitHub Projects V2 — ${org}`,
    "",
    ...(items.length === 0
      ? ["(no Projects V2 boards found for this owner)"]
      : items.map((p) => `- **${p.title}** — number ${p.number}, id \`${p.id}\``)),
    "",
  ];
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, lines.join("\n"), "utf8");
  process.stdout.write(`detect: ${items.length} board(s) for ${org} → ${outPath}\n`);
}

interface Project {
  title: string;
  number: number;
  id: string;
}
function isProjectList(v: unknown): v is { projects: Project[] } {
  return (
    typeof v === "object" &&
    v !== null &&
    Array.isArray((v as { projects?: unknown }).projects)
  );
}
